- name: Install and configure NGINX on web hosts
  hosts: webservers
  become: true
  vars:
    tfstate_path: "../terraform/terraform.tfstate"
    db_name: mydb
    db_user: postgres
    db_port: 5432
    #ansible_python_interpreter: /opt/hostedtoolcache/Python/3.12.3/x64/bin/python
    
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure NGINX is running and enabled
      service:
        name: nginx
        state: started
        enabled: true

    - name: Get the hostname
      command: hostname
      register: hostname_output

    - name: Read terraform.tfstate
      slurp:
        src: "{{ tfstate_path }}"
      register: raw_tfstate
      delegate_to: localhost

    - name: Parse tfstate JSON
      ansible.builtin.set_fact:
        tfstate: "{{ raw_tfstate.content | b64decode | from_json }}"
      delegate_to: localhost
        
    - name: Extract postgres hostname
      set_fact:
        db_host: "{{ tfstate.outputs.postgres_endpoint.value.split(':')[0] }}"
      delegate_to: localhost
      
    - name: Read content from PostgreSQL
      community.postgresql.postgresql_query:
        db: "{{ db_name }}"
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        port: "{{ db_port }}"
        query: SELECT * FROM cars;
      register: query_result
      no_log: true
      vars:
        ansible_python_interpreter: /opt/hostedtoolcache/Python/3.12.3/x64/bin/python
      delegate_to: localhost

    - name: Show query results for debugging (optional)
      debug:
        var: query_result
      delegate_to: localhost
        
    - name: Create index.html with Hello World and hostname
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <style>
              table {
                background-color: teal;
                color: white;
                border: 2px solid teal;
                border-radius: 10px;
                width: 300px;
                margin: 100px auto;
                text-align: center;
                font-family: Arial, sans-serif;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
              }
          
              td {
                padding: 20px;
                border-bottom: 1px solid white;
              }
          
              tr:last-child td {
                border-bottom: none;
              }
            </style>
          </head>
          <body>
          
            <table>
              <tr>
                <td>Hello World!</td>
              </tr>
              <tr>
                <td>{{ hostname_output }}</td>
              </tr>
              <tr>
                <td>{{ query_result }}</td>
              </tr>
            </table>
          
          </body>
          </html>
