- name: Install and configure NGINX on web hosts
  hosts: web
  become: true
  vars:
    db_name: mydb
    db_user: postgres
    db_port: 5432
    ansible_python_interpreter: /opt/hostedtoolcache/Python/3.12.3/x64/bin/python
    
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure NGINX is running and enabled
      service:
        name: nginx
        state: started
        enabled: true

    - name: Get the hostname
      command: hostname
      register: hostname_output

    - name: Read terraform.tfstate
      slurp:
        src: "{{ tfstate_path }}"
      register: raw_tfstate

    - name: Parse tfstate JSON
      ansible.builtin.set_fact:
        tfstate: "{{ raw_tfstate.content | b64decode | from_json }}"
        
    - name: Extract postgres hostname
      set_fact:
        db_host: "{{ tfstate.outputs.postgres_endpoint.value.split(':')[0] }}"
      
    - name: Read content from PostgreSQL
      community.postgresql.postgresql_query:
        db: "{{ db_name }}"
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        port: "{{ db_port }}"
        query: SELECT * FROM cars;
      register: query_result
      no_log: true

    - name: Show query results for debugging (optional)
      debug:
        var: query_result
        
    - name: Create index.html with Hello World and hostname
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Hello</title></head>
          <body>
            <h1>Hello World</h1>
            <h2>I'm coming from Hostname: {{ hostname_output.stdout }}</h2>
            <h1>{{ query_result }}</h1>
          </body>
          </html>
