---
- name: Fetch Terraform state file from S3
  hosts: localhost
  gather_facts: no
  vars:
    bucket_name: msd-assignment-bucket
    object_key: terraform.tfstate
    region: ap-south-1
    local_state_file: /tmp/terraform.tfstate


  tasks:

    - name: Ensure AWS CLI is installed
      command: aws --version
      register: aws_cli_check
      ignore_errors: yes

    - name: Fail if AWS CLI is not installed
      fail:
        msg: "AWS CLI is not installed!"
      when: aws_cli_check.rc != 0

    - name: Download Terraform state file from S3
      command: >
        aws s3 cp s3://{{ bucket_name }}/{{ object_key }} {{ local_state_file }}
        --region {{ region }}
      register: s3_fetch_result


    - name: Read terraform.tfstate
      slurp:
        src: "{{ local_state_file }}"
      register: raw_tfstate

    - name: Parse tfstate JSON
      ansible.builtin.set_fact:
        tfstate: "{{ raw_tfstate.content | b64decode | from_json }}"

    - name: Show RDS Endpoint
      debug:
        var: tfstate
