---
- name: Fetch Terraform state file from S3
  hosts: localhost
  gather_facts: no
  vars:
    bucket_name: msd-assignment-bucket
    object_key: terraform.tfstate
    region: ap-south-1
    local_state_file: /tmp/terraform.tfstate

  tasks:

    - name: Ensure AWS CLI is installed
      command: aws --version
      register: aws_cli_check
      ignore_errors: yes

    - name: Fail if AWS CLI is not installed
      fail:
        msg: "AWS CLI is not installed!"
      when: aws_cli_check.rc != 0

    - name: Download Terraform state file from S3
      command: >
        aws s3 cp s3://{{ bucket_name }}/{{ object_key }} {{ local_state_file }}
        --region {{ region }}
      register: s3_fetch_result

    - name: Parse RDS endpoint from tfstate
      command: >
        jq -r '.resources[] 
          | select(.type == "aws_db_instance" and .name == "postgres") 
          | .instances[0].attributes.endpoint' {{ local_state_file }}
      register: rds_endpoint

    - name: Show RDS Endpoint
      debug:
        msg: "RDS Endpoint is {{ rds_endpoint.stdout }}"

    # Optional: set fact to use later
    - set_fact:
        db_host: "{{ rds_endpoint.stdout }}"
