---
- name: Create cars table and insert data into PostgreSQL
  hosts: localhost
  gather_facts: no
  vars:
    db_host: "msd-assignment-db.c7ey8cm4mc17.ap-south-1.rds.amazonaws.com"
    db_port: 5432
    db_name: "mydb"
    db_user: "postgres"
    db_password: "gokulan123"
    index_html_path: "/var/www/html/index.html"

  tasks:

    - name: Create cars table
      community.postgresql.postgresql_query:
        db: "{{ db_name }}"
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        port: "{{ db_port }}"
        query: |
          CREATE TABLE IF NOT EXISTS cars (
              id SERIAL PRIMARY KEY,
              brand TEXT,
              model TEXT,
              year INT
          );

    # - name: Insert car data
    #   community.postgresql.postgresql_query:
    #     db: "{{ db_name }}"
    #     login_host: "{{ db_host }}"
    #     login_user: "{{ db_user }}"
    #     login_password: "{{ db_password }}"
    #     port: "{{ db_port }}"
    #     query: |
    #       INSERT INTO cars (brand, model, year) VALUES
    #       ('Toyota', 'Corolla', 2020),
    #       ('Honda', 'Civic', 2019),
    #       ('Ford', 'Mustang', 2021);


    # - name: Read content from PostgreSQL
    #   community.postgresql.postgresql_query:
    #     db: "{{ db_name }}"
    #     login_host: "{{ db_host }}"
    #     login_user: "{{ db_user }}"
    #     login_password: "{{ db_password }}"
    #     port: "{{ db_port }}"
    #     query: "SELECT * FROM cars;"
    #   register: query_result

    # - name: Show query results for debugging (optional)
    #   debug:
    #     var: query_result

    - name: Append content to index.html
      copy:
        content: |
          {% for row in query_result.query_result %}
          <p>{{ row.content }}</p>
          {% endfor %}
        dest: "{{ index_html_path }}"
        owner: www-data
        group: www-data
        mode: '0644'
        force: no
      when: query_result.query_result is defined
