name: Assignment Pipeline

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Select Terraform Action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: write # Required to push to github

jobs:
  Infra-As-Code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Show Terraform version
        run: terraform -version

      - name: Configure AWS credentials (Use Open ID Connect)
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/msd-tech-assignment-aws-role
          aws-region: ap-south-1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Run Terraform Apply or Destroy
        working-directory: ./terraform
        run: |
          if [ "${{ github.event.inputs.terraform_action }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ github.event.inputs.terraform_action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action: ${{ github.event.inputs.terraform_action }}"
            exit 1
          fi

      - name: Commit terraform state to repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add terraform/terraform.tfstate terraform/.terraform.lock.hcl
          git commit -m "Save Terraform state after ${{ github.event.inputs.terraform_action }}"
          git push

 # ---------------------- Start Ansible Integration ---------------------------------------------- # 
 
  Config-As-Code:
    runs-on: ubuntu-latest
    needs: Infra-As-Code
    if: ${{ github.event.inputs.terraform_action == 'apply' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Pull latest changes from main branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull origin main

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          sudo ansible --version
          sudo ansible-galaxy --version

      - name: Save SSH Key from Secret
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/msd_assignment_key.pem
          chmod 600 ~/.ssh/msd_assignment_key.pem

      - name: Run Ansible Playbook - create inventories.ini file
        run: |
          ansible-playbook ansible/main.yml
          
      - name: Run Ansible Playbook - install webservers from inventories.ini file
        run: |
          ansible-playbook ansible/configure_webservers.yml -i ansible/inventories.ini \
            --private-key ~/.ssh/msd_assignment_key.pem

      - name: Commit Ansible output (if any)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ansible/inventories.ini || true
          git commit -m "Add Ansible output after apply" || echo "No changes"
          git push
