name: Manual Setup - Terraform & Ansible

on:
  workflow_dispatch:  # Only run manually from the GitHub Actions UI
  
permissions:
  id-token: write   # This is required for requesting the JWT

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2 

      - name: Show Terraform version
        run: terraform -version

      # - name: Install Ansible
      #   run: |
      #     sudo apt update
      #     sudo apt install -y ansible

      # - name: Show Ansible version
      #   run: ansible --version

      - name: Configure AWS credentials (Use Open ID Connect)
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::975050221465:role/msd-tech-assignment-aws-role
          aws-region: ap-south-1
          

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform init && terraform apply -auto-approve
